{"additions": 44, "auther_ref": "FixTSFF", "auther_sha": "29a097f939dc1cb68089b0e0bcd13c27b6095f2d", "author": "VinInn", "body": "catch \"buffer full\" before insertion (as in pre-threadSafe version).\nprint LogError (as in pre-threadSafe version).\ntested with runTheMatrix and addOnTests.py -t hlt_data_GRun reducing the capacity to 10K...\n\nwill recompile the universe\n", "branch": "CMSSW_8_1_X", "changed_files": 3, "closed_at": "1471944036", "comments": 9, "commits": 3, "created_at": "1471700242", "deletions": 9, "labels": ["comparison-available", "core-approved", "fully-signed", "orp-pending", "reconstruction-approved", "tests-rejected"], "merge_commit_sha": "55471ec7afe103c6c544c192214bc4240bae7a77", "merged_at": "1471944036", "merged_by": "davidlange6", "milestone": "Next CMSSW_8_1_X", "number": 15529, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fix throwing CapacityExausted", "updated_at": "1471944036", "user": "VinInn"}