{"additions": 60, "auther_ref": "throwLumiSynchronize", "auther_sha": "0910e65c53a0713a1ea20a0244fa63a0872a92f4", "author": "makortel", "body": "#### PR description:\r\n\r\nFollowing the completion of #25090. This PR simply turns an existing warning to an exception. It also addresses framework unit tests that would fail because of the exception. It is possible that some unit tests in other packages would fail too (in which case I'll address those separately).\r\n\r\nResolves https://github.com/makortel/framework/issues/121\r\n\r\n#### PR validation:\r\n\r\nFramework unit tests run.", "branch": "master", "changed_files": 10, "comments": 18, "commits": 3, "created_at": "1631899064", "deletions": 38, "labels": ["core-pending", "pending-signatures", "tests-rejected", "orp-pending", "code-checks-approved"], "milestone": "CMSSW_12_1_X", "number": 35326, "release-notes": [], "review_comments": 0, "state": "open", "title": "Throw an exception if a module requiring synchronization on lumi boundaries is used when concurrent lumis are enabled", "updated_at": "1632803587", "user": "makortel"}