{"additions": 34, "auther_ref": "exception_when_new_sources_75x", "auther_sha": "7d822ef8da0d59f7b30b862d67931288b59e36ca", "author": "bbockelm", "body": "If a read call was performed after XrdFile threw an exception, it\nis possible there are no active sources.  However, not all paths\ncheck for the case of zero sources and may use-after-free the last\nsource.\n\nThis caused a deadlock at the Tier-0.\n\n(cherry picked from commit a012aaf9a27aaf416c4a2e1e4e1f5409ca2c760d)\n", "branch": "CMSSW_7_5_X", "changed_files": 1, "closed_at": "1448892404", "comments": 3, "commits": 1, "created_at": "1448892160", "deletions": 1, "labels": ["comparison-pending", "core-pending", "orp-pending", "pending-signatures", "tests-pending"], "milestone": "CMSSW_7_5_X", "number": 12606, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fail read calls after exception.", "updated_at": "1448892404", "user": "bbockelm"}