{"additions": 18, "auther_ref": "fix-py2-dxr-linux-76x-next", "auther_sha": "fd240d90b29358c6d47c24195f93cd7654664e53", "author": "gartung", "body": "Merge conflict in Requires lines. Please take mine\n", "branch": "IB/CMSSW_7_6_X/next", "changed_files": 2, "closed_at": "1444718240", "comments": 4, "commits": 2, "created_at": "1444648725", "deletions": 6, "labels": [], "merge_commit_sha": "fd79ddb911bb9b0890bd6c66767e63a29bc0d86a", "merged_at": "1444718240", "merged_by": "degano", "number": 1884, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fix py2 dxr linux 76x next", "updated_at": "1506441980", "user": "gartung"}