{"additions": 0, "auther_ref": "fix_pandas_75X", "auther_sha": "0e08d96bc94bf303cbd74a4c25f048ae165c45b9", "author": "degano", "body": "", "branch": "IB/CMSSW_7_5_X/stable", "changed_files": 1, "closed_at": "1430890798", "comments": 0, "commits": 1, "created_at": "1430890788", "deletions": 1, "labels": [], "merge_commit_sha": "248c033c1d0470be4ee933d028ef5baaa3c67c5a", "merged_at": "1430890798", "merged_by": "degano", "number": 1526, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fix non-existing path in py2-pandas-toolfile.", "updated_at": "1430890800", "user": "degano"}