{"additions": 1, "auther_ref": "correctforall", "auther_sha": "d5fcd95d3f2aa89ac083d6529d50b05c5d1923dc", "author": "apsallid", "body": "#### PR description:\r\n\r\nThere is a crash in the 'makeHGCalValidationPlots.py' when using the `--collection all` option related to python3. I don't know how this one got away, but now it's OK, when using `--collection all` there is no crash. \r\n\r\nThanks @ebrondol for the alert on the problem.\r\n\r\n#### PR validation:\r\n\r\nLocal validation. \r\n\r\n#### if this PR is a backport please specify the original PR and why you need to backport that PR:\r\n\r\nThis is not a backport. \r\n\r\n@rovere @felicepantaleo @lecriste @ebrondol ", "branch": "master", "changed_files": 1, "comments": 3, "commits": 1, "created_at": "1635951040", "deletions": 1, "labels": ["dqm-pending", "pending-signatures", "orp-pending", "tests-started", "code-checks-approved"], "milestone": "CMSSW_12_2_X", "number": 35973, "release-notes": [], "review_comments": 0, "state": "open", "title": "[HGCAL] makeHGCalValidationPlots.py crash due to python3", "updated_at": "1636038516", "user": "apsallid"}