{"additions": 1, "auther_ref": "patch-5", "auther_sha": "8ca870aec266e6e7798a8368ca2ae9a20563932b", "author": "iarspider", "body": "#### PR description:\r\n\r\nThe attribute containing exception message is different Python in 2.7 vs. 3.x, also the message itself is not very useful.\r\nTechnical fix following #37727", "branch": "master", "changed_files": 1, "closed_at": "1651754022", "comments": 7, "commits": 1, "created_at": "1651727582", "deletions": 1, "labels": ["core-approved", "fully-signed", "tests-approved", "orp-approved", "code-checks-approved"], "merge_commit_sha": "ae61a8ebe5fad2b42dca915278f0fe0ac247abf5", "merged_at": "1651754022", "merged_by": "cmsbuild", "milestone": "CMSSW_12_4_X", "number": 37809, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Update cppCommentSkipper: don't log the exact error", "updated_at": "1651754023", "user": "iarspider"}